version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ????????      # Coloque sua senha aqui
      POSTGRES_DB: predimec
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../sql:/docker-entrypoint-initdb.d   # <-- Adicione esta linha

volumes:
  postgres_data: